[package]
name = "dataplane"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
thiserror = "2"

tracing = "0.1"
tracing-subscriber = "0.3"

libc = "0.2"

nix = { version = "0.30", features = ["sched", "process", "mount", "fs", "user", "signal"] }
uuid = { version = "1.23.3", features = ["v4"] }
